In [4]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score,classification_report
from sklearn.preprocessing import PowerTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
import matplotlib.pyplot as plt

C:\anaconda\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [5]:
data_train=pd.read_csv(r"C:\Users\manab\Downloads\DEEP LEARNING PROJECTS\Cirrhosis  Prediction\train.csv")
data_test=pd.read_csv(r"C:\Users\manab\Downloads\DEEP LEARNING PROJECTS\Cirrhosis  Prediction\test.csv")

In [6]:
data_train.head()

,id,N_Days,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage,Status
0,0,999,D-penicillamine,21532,M,N,N,N,N,2.3,316.0,3.35,172.0,1601.0,179.80,63.0,394.0,9.7,3.0,D
1,1,2574,Placebo,19237,F,N,N,N,N,0.9,364.0,3.54,63.0,1440.0,134.85,88.0,361.0,11.0,3.0,C
2,2,3428,Placebo,13727,F,N,Y,Y,Y,3.3,299.0,3.55,131.0,1029.0,119.35,50.0,199.0,11.7,4.0,D
3,3,2576,Placebo,18460,F,N,N,N,N,0.6,256.0,3.50,58.0,1653.0,71.30,96.0,269.0,10.7,3.0,C
4,4,788,Placebo,16658,F,N,Y,N,N,1.1,346.0,3.65,63.0,1181.0,125.55,96.0,298.0,10.6,4.0,C

In [7]:
data_train.isnull().sum()

id               0
N_Days           0
Drug             0
Age              0
Sex              0
Ascites          0
Hepatomegaly     0
Spiders          0
Edema            0
Bilirubin        0
Cholesterol      0
Albumin          0
Copper           0
Alk_Phos         0
SGOT             0
Tryglicerides    0
Platelets        0
Prothrombin      0
Stage            0
Status           0
dtype: int64

In [8]:
data_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7905 entries, 0 to 7904
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             7905 non-null   int64
 1   N_Days         7905 non-null   int64
 2   Drug           7905 non-null   object
 3   Age            7905 non-null   int64
 4   Sex            7905 non-null   object
 5   Ascites        7905 non-null   object
 6   Hepatomegaly   7905 non-null   object
 7   Spiders        7905 non-null   object
 8   Edema          7905 non-null   object
 9   Bilirubin      7905 non-null   float64
 10  Cholesterol    7905 non-null   float64
 11  Albumin        7905 non-null   float64
 12  Copper         7905 non-null   float64
 13  Alk_Phos       7905 non-null   float64
 14  SGOT           7905 non-null   float64
 15  Tryglicerides  7905 non-null   float64
 16  Platelets      7905 non-null   float64
 17  Prothrombin    7905 non-null   float64
 18  Stage          7905 non-null   float64
 19  Status         7905 non-null   object
dtypes: float64(10), int64(3), object(7)
memory usage: 1.2+ MB

In [9]:
data_train.describe()

,id,N_Days,Age,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage
count,7905.000000,7905.000000,7905.000000,7905.000000,7905.000000,7905.000000,7905.000000,7905.000000,7905.000000,7905.000000,7905.000000,7905.000000,7905.000000
mean,3952.000000,2030.173308,18373.146490,2.594485,350.561923,3.548323,83.902846,1816.745250,114.604602,115.340164,265.228969,10.629462,3.032511
std,2282.121272,1094.233744,3679.958739,3.812960,195.379344,0.346171,75.899266,1903.750657,48.790945,52.530402,87.465579,0.781735,0.866511
min,0.000000,41.000000,9598.000000,0.300000,120.000000,1.960000,4.000000,289.000000,26.350000,33.000000,62.000000,9.000000,1.000000
25%,1976.000000,1230.000000,15574.000000,0.700000,248.000000,3.350000,39.000000,834.000000,75.950000,84.000000,211.000000,10.000000,2.000000
50%,3952.000000,1831.000000,18713.000000,1.100000,298.000000,3.580000,63.000000,1181.000000,108.500000,104.000000,265.000000,10.600000,3.000000
75%,5928.000000,2689.000000,20684.000000,3.000000,390.000000,3.770000,102.000000,1857.000000,137.950000,139.000000,316.000000,11.000000,4.000000
max,7904.000000,4795.000000,28650.000000,28.000000,1775.000000,4.640000,588.000000,13862.400000,457.250000,598.000000,563.000000,18.000000,4.000000

In [10]:
data_train.shape

(7905, 20)

In [13]:
data_train['Status'].value_counts()

C     4965
D     2665
CL     275
Name: Status, dtype: int64

In [14]:
data_train['Drug'].value_counts()

Placebo            4010
D-penicillamine    3895
Name: Drug, dtype: int64

In [16]:
data_train.drop(['N_Days'],axis=1,inplace=True)
data_test.drop(['N_Days'],axis=1,inplace=True)

In [18]:
columns=['Sex','Ascites','Hepatomegaly','Spiders','Edema','Drug']
le=LabelEncoder()

data_train['Status']=le.fit_transform(data_train['Status'])

for i in columns:
    data_train[i]=le.fit_transform(data_train[i])
    data_test[i]=le.fit_transform(data_test[i])

In [19]:
data_train.head()

,id,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage,Status
0,0,0,21532,1,0,0,0,0,2.3,316.0,3.35,172.0,1601.0,179.80,63.0,394.0,9.7,3.0,2
1,1,1,19237,0,0,0,0,0,0.9,364.0,3.54,63.0,1440.0,134.85,88.0,361.0,11.0,3.0,0
2,2,1,13727,0,0,1,1,2,3.3,299.0,3.55,131.0,1029.0,119.35,50.0,199.0,11.7,4.0,2
3,3,1,18460,0,0,0,0,0,0.6,256.0,3.50,58.0,1653.0,71.30,96.0,269.0,10.7,3.0,0
4,4,1,16658,0,0,1,0,0,1.1,346.0,3.65,63.0,1181.0,125.55,96.0,298.0,10.6,4.0,0

In [24]:
sc=StandardScaler()
columns_to_scale=['Age','Cholesterol','Albumin','Copper','Alk_Phos','SGOT','Tryglicerides','Platelets','Prothrombin','Stage']
data_train[columns_to_scale]=sc.fit_transform(data_train[columns_to_scale])
data_test[columns_to_scale]=sc.transform(data_test[columns_to_scale])

In [25]:
data_train.head()

,id,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage,Status
0,0,0,0.858448,1,0,0,0,0,2.3,-0.176908,-0.572940,1.160785,-0.113334,1.336304,-0.996442,1.472341,-1.189049,-0.037522,2
1,1,1,0.234760,0,0,0,0,0,0.9,0.068784,-0.024043,-0.275420,-0.197909,0.414968,-0.520497,1.095026,0.474024,-0.037522,0
2,2,1,-1.262634,0,0,1,1,2,3.3,-0.263923,0.004846,0.620561,-0.413812,0.097266,-1.243933,-0.757248,1.369525,1.116605,2
3,3,1,0.023603,0,0,0,0,0,0.6,-0.484022,-0.139601,-0.341301,-0.086017,-0.887610,-0.368194,0.043117,0.090238,-0.037522,0
4,4,1,-0.466107,0,0,1,0,0,1.1,-0.023351,0.293739,-0.275420,-0.333965,0.224347,-0.368194,0.374697,-0.037691,1.116605,0

In [26]:
data_test.head()

,id,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage
0,7905,0,0.367107,0,0,1,0,0,1.2,1.000364,-0.515161,-0.249068,-0.094948,0.764440,-0.482421,1.883958,-0.037691,-1.191649
1,7906,0,-0.923478,0,0,0,0,0,1.1,1.583881,1.940429,0.133042,-0.294041,0.764440,0.755036,-0.437102,-0.805263,-1.191649
2,7907,1,-1.419711,0,0,1,0,2,2.0,-1.021472,-1.699623,-0.499415,-0.449533,-0.919380,-0.273005,-0.597175,3.032598,1.116605
3,7908,0,0.580710,0,0,0,0,0,0.6,-0.294635,0.871525,-0.578472,-0.663335,0.224347,-1.129706,0.054551,-0.037691,-1.191649
4,7909,0,0.959543,0,0,1,0,0,1.4,-0.376532,-1.670733,0.488799,-0.371262,0.213073,0.202940,-0.505705,-1.061120,-2.345776

In [29]:
from sklearn.preprocessing import RobustScaler, QuantileTransformer
import pandas as pd

# Assuming 'train' and 'test' are your dataframes
columns_to_scale = ['Age', 'Cholesterol', 'Albumin', 'Copper', 'Alk_Phos', 'SGOT', 'Tryglicerides', 'Platelets', 'Prothrombin', 'Stage']

# Robust Scaling
robust_scaler = RobustScaler()
data_train[columns_to_scale] = robust_scaler.fit_transform(data_train[columns_to_scale])
data_test[columns_to_scale] = robust_scaler.transform(data_test[columns_to_scale])

from sklearn.preprocessing import QuantileTransformer

quantile_transformer = QuantileTransformer(output_distribution='normal')
data_train[columns_to_scale] = quantile_transformer.fit_transform(data_train[columns_to_scale])
data_test[columns_to_scale] = quantile_transformer.transform(data_test[columns_to_scale])

In [31]:
data_train.head()

,id,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage,Status
0,0,0,0.844485,1,0,0,0,0,2.3,0.177827,-0.718462,1.269664,0.395204,1.343287,-1.275302,1.378114,-1.460531,-0.104318,2
1,1,1,0.186756,0,0,0,0,0,0.9,0.522099,-0.153660,-0.006273,0.283522,0.565738,-0.497809,1.207532,0.630254,-0.104318,0
2,2,1,-1.184447,0,0,1,1,2,3.3,0.012546,-0.121995,0.985610,-0.321611,0.172731,-2.307607,-0.832006,1.378114,5.199338,2
3,3,1,-0.025094,0,0,0,0,0,0.6,-0.533636,-0.276998,-0.082896,0.480839,-0.893908,-0.217488,0.119468,0.252311,-0.104318,0
4,4,1,-0.427976,0,0,1,0,0,1.1,0.400635,0.278302,-0.006273,0.005018,0.321611,-0.217488,0.468203,0.046436,5.199338,0

In [32]:
x=data_train.drop('Status',axis=1)
y=data_train['Status']

In [33]:
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.2,random_state=42)

In [35]:
rf_classifier = RandomForestClassifier(
    max_depth=10,
    min_samples_leaf=2,
    min_samples_split=5,
    n_estimators=200
)

rf_classifier.fit(x_train, y_train)

RandomForestClassifier(max_depth=10, min_samples_leaf=2, min_samples_split=5,
                       n_estimators=200)

In [36]:
y_pred = rf_classifier.predict(x_test)

In [38]:
acc = accuracy_score(y_test, y_pred)
print("Accuracy:",acc)
cr=classification_report(y_test, y_pred)
print("Classification report:\n",cr)

Accuracy: 0.814674256799494
Classification report:
               precision    recall  f1-score   support

           0       0.82      0.92      0.87       966
           1       1.00      0.02      0.04        52
           2       0.81      0.70      0.75       563

    accuracy                           0.81      1581
   macro avg       0.88      0.55      0.55      1581
weighted avg       0.82      0.81      0.80      1581

In [39]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Assuming x_train and x_test are your feature matrices and y_train, y_test are your target variables

# Define the neural network model
model = Sequential()
model.add(Dense(64, input_dim=x_train.shape[1], activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='sigmoid'))  # For binary classification

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(x_train, y_train, epochs=10, batch_size=32, validation_data=(x_test, y_test))

# Evaluate the model on the test set
test_loss, test_accuracy = model.evaluate(x_test, y_test)
print(f'Test Accuracy: {test_accuracy * 100:.2f}%')

WARNING:tensorflow:From C:\anaconda\lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

WARNING:tensorflow:From C:\anaconda\lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From C:\anaconda\lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

Epoch 1/10
WARNING:tensorflow:From C:\anaconda\lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From C:\anaconda\lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

198/198 [==============================] - 5s 6ms/step - loss: 25.4728 - accuracy: 0.2192 - val_loss: 1.4600 - val_accuracy: 0.5655
Epoch 2/10
198/198 [==============================] - 0s 2ms/step - loss: 2.2777 - accuracy: 0.2552 - val_loss: -1.5461 - val_accuracy: 0.4586
Epoch 3/10
198/198 [==============================] - 0s 2ms/step - loss: -0.0332 - accuracy: 0.2838 - val_loss: 0.7045 - val_accuracy: 0.0715
Epoch 4/10
198/198 [==============================] - 0s 2ms/step - loss: -1.4065 - accuracy: 0.2932 - val_loss: -7.5513 - val_accuracy: 0.2245
Epoch 5/10
198/198 [==============================] - 0s 2ms/step - loss: -6.7706 - accuracy: 0.3042 - val_loss: -14.0881 - val_accuracy: 0.4181
Epoch 6/10
198/198 [==============================] - 0s 2ms/step - loss: -15.0643 - accuracy: 0.3180 - val_loss: -27.3086 - val_accuracy: 0.3877
Epoch 7/10
198/198 [==============================] - 0s 2ms/step - loss: -28.6111 - accuracy: 0.3091 - val_loss: -57.8496 - val_accuracy: 0.1183
Epoch 8/10
198/198 [==============================] - 0s 2ms/step - loss: -69.5881 - accuracy: 0.3142 - val_loss: -112.7919 - val_accuracy: 0.4130
Epoch 9/10
198/198 [==============================] - 0s 2ms/step - loss: -129.7668 - accuracy: 0.3185 - val_loss: -234.9583 - val_accuracy: 0.2353
Epoch 10/10
198/198 [==============================] - 0s 2ms/step - loss: -250.0625 - accuracy: 0.3186 - val_loss: -417.6192 - val_accuracy: 0.3814
50/50 [==============================] - 0s 2ms/step - loss: -417.6192 - accuracy: 0.3814
Test Accuracy: 38.14%